blank_issues_enabled: true
contact_links:
  - name: Arte Support
    url: https://t.me/SonSahip
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/SonSahip
    about: Documentation for getting started with bot.
